name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - run: mkdir -p ./src/main/resources
      working-directory: ./backend

    - run: touch ./src/main/resources/application-api.properties
      working-directory: ./backend
    - run: echo "${{ secrets.API_PROPERTIES }}" > ./src/main/resources/application-api.properties
      working-directory: ./backend
    - run: cat ./src/main/resources/application-api.properties
      working-directory: ./backend

    - run: touch ./src/main/resources/application-security.properties
      working-directory: ./backend
    - run: echo "${{ secrets.SECURITY_PROPERTIES }}" > ./src/main/resources/application-security.properties
      working-directory: ./backend
    - run: cat ./src/main/resources/application-security.properties
      working-directory: ./backend

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.7'

    - name: Set Gradle Wrapper executable permission
      run: chmod +x ./backend/gradlew

    - name: Build with Gradle Wrapper
      run: ./backend/gradlew build
      working-directory: ./backend

